apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-namespace
  namespace: backend
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: frontend
    - from:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: backend
               
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP

    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: frontend

    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: backend
