---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-namespace
  namespace: frontend
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: backend
    - from:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: frontend               
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: backend
    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: frontend

